package com.testyourskills.entitybean;
// Generated Jan 2, 2017 2:30:23 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnswerBean generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "skilldb")
public class AnswerBean implements java.io.Serializable {

	private Long answerId;
	private OptionsBean options;
	private QuestionBean question;

	public AnswerBean() {
	}

	public AnswerBean(QuestionBean question) {
		this.question = question;
	}

	public AnswerBean(OptionsBean options, QuestionBean question) {
		this.options = options;
		this.question = question;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ANSWER_ID", unique = true, nullable = false)
	public Long getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Long answerId) {
		this.answerId = answerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPTION_ID")
	public OptionsBean getOptions() {
		return this.options;
	}

	public void setOptions(OptionsBean options) {
		this.options = options;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID", nullable = false)
	public QuestionBean getQuestion() {
		return this.question;
	}

	public void setQuestion(QuestionBean question) {
		this.question = question;
	}

}
