package com.testyourskills.entitybean;
// Generated Nov 26, 2016 12:50:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnswerBean generated by hbm2java
 */
@Entity
@Table(name = "ANSWER")
public class AnswerBean implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9212769628308144916L;
	private Long answerId;
	private QuestionBean questionBean;
	private OptionsBean optionsBean;

	public AnswerBean() {
	}


	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ANSWER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Long answerId) {
		this.answerId = answerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID", nullable = false)
	public QuestionBean getQuestion() {
		return this.questionBean;
	}

	public void setQuestion(QuestionBean questionBean) {
		this.questionBean = questionBean;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPTION_ID")
	public OptionsBean getOptions() {
		return this.optionsBean;
	}

	public void setOptions(OptionsBean optionsBean) {
		this.optionsBean = optionsBean;
	}

}
