package com.testyourskills.entitybean;
// Generated Jan 2, 2017 2:30:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OptionsBean generated by hbm2java
 */
@Entity
@Table(name = "options", catalog = "skilldb")
public class OptionsBean implements java.io.Serializable {

	private Long optionId;
	private QuestionBean question;
	private String optnDesc;
	private Set<AnswerBean> answers = new HashSet<AnswerBean>(0);

	public OptionsBean() {
	}

	public OptionsBean(QuestionBean question, String optnDesc) {
		this.question = question;
		this.optnDesc = optnDesc;
	}

	public OptionsBean(QuestionBean question, String optnDesc, Set<AnswerBean> answers) {
		this.question = question;
		this.optnDesc = optnDesc;
		this.answers = answers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OPTION_ID", unique = true, nullable = false)
	public Long getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Long optionId) {
		this.optionId = optionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID", nullable = false)
	public QuestionBean getQuestion() {
		return this.question;
	}

	public void setQuestion(QuestionBean question) {
		this.question = question;
	}

	@Column(name = "OPTN_DESC", nullable = false, length = 2048)
	public String getOptnDesc() {
		return this.optnDesc;
	}

	public void setOptnDesc(String optnDesc) {
		this.optnDesc = optnDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "options")
	public Set<AnswerBean> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<AnswerBean> answers) {
		this.answers = answers;
	}

}
