package com.testyourskills.entitybean;
// Generated Nov 26, 2016 12:50:39 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionBean generated by hbm2java
 */
@Entity
@Table(name = "QUESTION")
public class QuestionBean implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2147946795677163510L;
	private Long questionId;
	private ValidTopicBean validTopicBean;
	private String qnDesc;
	private Set<OptionsBean> optionses = new HashSet<OptionsBean>(0);
	private Set<AnswerBean> answerBeans = new HashSet<AnswerBean>(0);

	public QuestionBean() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "QUESTION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOPIC_ID", nullable = false)
	public ValidTopicBean getValidTopic() {
		return this.validTopicBean;
	}

	public void setValidTopic(ValidTopicBean validTopicBean) {
		this.validTopicBean = validTopicBean;
	}
	@Lob
	@Column(name = "QN_DESC")
	public String getQnDesc() {
		return this.qnDesc;
	}

	public void setQnDesc(String qnDesc) {
		this.qnDesc = qnDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<OptionsBean> getOptionses() {
		return this.optionses;
	}

	public void setOptionses(Set<OptionsBean> optionses) {
		this.optionses = optionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<AnswerBean> getAnswers() {
		return this.answerBeans;
	}

	public void setAnswers(Set<AnswerBean> answerBeans) {
		this.answerBeans = answerBeans;
	}

}
