package com.testyourskills.entitybean;
// Generated Jan 2, 2017 2:30:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionBean generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "skilldb")
public class QuestionBean implements java.io.Serializable {

	private Long questionId;
	private ValidTopicBean validTopic;
	private String qnDesc;
	private Set<AnswerBean> answers = new HashSet<AnswerBean>(0);
	private Set<OptionsBean> optionses = new HashSet<OptionsBean>(0);

	public QuestionBean() {
	}

	public QuestionBean(ValidTopicBean validTopic) {
		this.validTopic = validTopic;
	}

	public QuestionBean(ValidTopicBean validTopic, String qnDesc, Set<AnswerBean> answers, Set<OptionsBean> optionses) {
		this.validTopic = validTopic;
		this.qnDesc = qnDesc;
		this.answers = answers;
		this.optionses = optionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "QUESTION_ID", unique = true, nullable = false)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOPIC_ID", nullable = false)
	public ValidTopicBean getValidTopic() {
		return this.validTopic;
	}

	public void setValidTopic(ValidTopicBean validTopic) {
		this.validTopic = validTopic;
	}

	@Column(name = "QN_DESC")
	public String getQnDesc() {
		return this.qnDesc;
	}

	public void setQnDesc(String qnDesc) {
		this.qnDesc = qnDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<AnswerBean> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<AnswerBean> answers) {
		this.answers = answers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<OptionsBean> getOptionses() {
		return this.optionses;
	}

	public void setOptionses(Set<OptionsBean> optionses) {
		this.optionses = optionses;
	}

}
