package com.testyourskills.entitybean;
// Generated Nov 26, 2016 12:50:39 AM by Hibernate Tools 4.3.1

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "QUESTION")
public class Question implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2147946795677163510L;
	private Long questionId;
	private ValidTopic validTopic;
	private Blob qnDesc;
	private Set<Options> optionses = new HashSet<Options>(0);
	private Set<Answer> answers = new HashSet<Answer>(0);

	public Question() {
	}

	@Id

	@Column(name = "QUESTION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Long questionId) {
		this.questionId = questionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOPIC_ID", nullable = false)
	public ValidTopic getValidTopic() {
		return this.validTopic;
	}

	public void setValidTopic(ValidTopic validTopic) {
		this.validTopic = validTopic;
	}

	@Column(name = "QN_DESC")
	public Blob getQnDesc() {
		return this.qnDesc;
	}

	public void setQnDesc(Blob qnDesc) {
		this.qnDesc = qnDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<Options> getOptionses() {
		return this.optionses;
	}

	public void setOptionses(Set<Options> optionses) {
		this.optionses = optionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
