package com.testyourskills.entitybean;
// Generated Jan 2, 2017 2:30:23 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsersBean generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "skilldb")
public class UsersBean implements java.io.Serializable {

	private Long userId;
	private String password;
	private String userName;

	public UsersBean() {
	}

	public UsersBean(String password, String userName) {
		this.password = password;
		this.userName = userName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_ID", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "PASSWORD", nullable = false, length = 10)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USER_NAME", nullable = false, length = 200)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
