package com.testyourskills.entitybean;
// Generated Jan 2, 2017 2:30:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@NamedQueries({
	@NamedQuery(name="getCategory",query="from ValidCategoryBean vcb where vcb.categoryName=:categoryName ")
})
/**
 * ValidCategoryBean generated by hbm2java
 */
@Entity
@Table(name = "valid_category", catalog = "skilldb")
public class ValidCategoryBean implements java.io.Serializable {

	private long categoryId;
	private String categoryName;
	private Set<ValidTopicBean> validTopics = new HashSet<ValidTopicBean>(0);

	public ValidCategoryBean() {
	}

	public ValidCategoryBean(long categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public ValidCategoryBean(long categoryId, String categoryName, Set<ValidTopicBean> validTopics) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.validTopics = validTopics;
	}

	@Id

	@Column(name = "CATEGORY_ID", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CATEGORY_NAME", nullable = false, length = 200)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "validCategory")
	public Set<ValidTopicBean> getValidTopics() {
		return this.validTopics;
	}

	public void setValidTopics(Set<ValidTopicBean> validTopics) {
		this.validTopics = validTopics;
	}

}
