package com.testyourskills.entitybean;
// Generated Nov 26, 2016 12:50:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ValidCategory generated by hbm2java
 */
@Entity
@Table(name = "VALID_CATEGORY")
public class ValidCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6909061014727379424L;
	private Long categoryId;
	private String categoryName;

	public ValidCategory() {
	}

	@Id

	@Column(name = "CATEGORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CATEGORY_NAME", nullable = false, length = 200)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}
